### ISSUE TITLE
Core dump when connecting to  SIGVerse

### ISSUE THREAD

**Issue by ArefMq** [SIGVerse/sigverse_ros_package#1]
Hi,

I am new to ROS and SIGVerse. I am trying to run a SIGVerse unity project in windows and connect it to a SIGVerse_ROS_Bridge in ubuntu. However, when the connection established, the SIGVerse_ROS_Bridge gets a segmentation fault. I have traced the error, it happens at this function 

callbsonCore.concatenate(bsonView);

I would be glad if anyone have a hint how can I fix this problem.

**Comment by hiroki-yamada** [comment]
I couldn't reproduce it, but I have initialized dummyArgc with the advice of another person.
https://github.com/SIGVerse/sigverse_ros_package/commit/c02a2d10b6a8d144c4b73680f34b5fd35bb8d608
